if(NOT DEFINED ROOT)
    message(FATAL_ERROR "ROOT variable must be provided")
endif()

get_filename_component(ROOT "${ROOT}" ABSOLUTE)

if(NOT DEFINED BINARY_DIR)
    message(FATAL_ERROR "BINARY_DIR variable must be provided")
endif()

get_filename_component(BINARY_DIR "${BINARY_DIR}" ABSOLUTE)

set(HGS_PATH "${BINARY_DIR}/hgs")
if(NOT EXISTS "${HGS_PATH}")
    message(FATAL_ERROR "Executable not found at ${HGS_PATH}. Build target 'bin' first.")
endif()

set(BASELINE_DIR "${ROOT}/baseline/vidal")
file(MAKE_DIRECTORY "${BASELINE_DIR}")

set(BASELINE_INSTANCES X-n101-k25 CMT6 CMT7)
set(BASELINE_ROUND 1 0 0)
set(BASELINE_SEED 1)

set(MANIFEST_CONTENT "instance,round,seed,cost\n")

list(LENGTH BASELINE_INSTANCES NB_INSTANCES)
math(EXPR LAST_INDEX "${NB_INSTANCES} - 1")

foreach(INDEX RANGE ${LAST_INDEX})
    list(GET BASELINE_INSTANCES ${INDEX} INSTANCE)
    list(GET BASELINE_ROUND ${INDEX} ROUND)

    set(SOLUTION_PATH "${BASELINE_DIR}/${INSTANCE}.sol")

    execute_process(
            COMMAND "${HGS_PATH}" "${ROOT}/Instances/CVRP/${INSTANCE}.vrp" "${SOLUTION_PATH}" -seed ${BASELINE_SEED} -round ${ROUND}
            WORKING_DIRECTORY "${BINARY_DIR}"
            RESULT_VARIABLE RUN_RESULT
    )

    if(NOT RUN_RESULT EQUAL 0)
        message(FATAL_ERROR "Baseline capture failed for ${INSTANCE}")
    endif()

    file(STRINGS "${SOLUTION_PATH}" SOLUTION_LINES)
    list(GET SOLUTION_LINES -1 LAST_LINE)
    string(REGEX MATCH "Cost[ ]+([-+0-9.eE]+)" COST_MATCH "${LAST_LINE}")
    if(NOT COST_MATCH)
        message(FATAL_ERROR "Could not parse cost for ${INSTANCE} from ${SOLUTION_PATH}")
    endif()

    string(REGEX REPLACE "Cost[ ]+" "" COST "${COST_MATCH}")
    string(APPEND MANIFEST_CONTENT "${INSTANCE},${ROUND},${BASELINE_SEED},${COST}\n")

    file(REMOVE "${SOLUTION_PATH}.PG.csv")
endforeach()

execute_process(
        COMMAND git rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${ROOT}"
        RESULT_VARIABLE GIT_RESULT
        OUTPUT_VARIABLE GIT_SHA
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
)

if(NOT GIT_RESULT EQUAL 0)
    set(GIT_SHA "unknown")
endif()

string(TIMESTAMP CAPTURED_UTC "%Y-%m-%dT%H:%M:%SZ" UTC)

string(CONCAT METADATA_CONTENT
    "baseline_name=vidal\n"
    "captured_utc=${CAPTURED_UTC}\n"
    "commit=${GIT_SHA}\n"
    "seed=${BASELINE_SEED}\n"
    "instances=X-n101-k25,CMT6,CMT7\n"
    "notes=Generated by Test/BaselineCapture.cmake\n")

file(WRITE "${BASELINE_DIR}/manifest.csv" "${MANIFEST_CONTENT}")
file(WRITE "${BASELINE_DIR}/metadata.txt" "${METADATA_CONTENT}")

message(STATUS "Baseline captured in ${BASELINE_DIR}")
